Documentation:
  Enabled: false

Style/LineLength:
  Max: 120
  Exclude: 
    - 'config/initializers/*'

Style/MethodLength:
  CountComments: false
  Max: 10
  Exclude:
    - 'db/migrate/*'

TrivialAccessors:
  Enabled: true
  ExactNameMatch: true

AllCops:
  RunRailsCops: true

